import createWallet from '../assets/shared.svg';

const env = import.meta.env || process.env;
const { PUBLIC_BASE_URL, PUBLIC_CRYPTO_PRIVATE_KEY, PUBLIC_PLATFORM_NAME, PUBLIC_PLATFORM_LOGO, PUBLIC_POWERED_BY, PUBLIC_PLATFORM_WEB_URL, PUBLIC_POWERED_BY_URL, PUBLIC_PLATFORM_DOCS_URL, PUBLIC_PLATFORM_GIT, PUBLIC_PLATFORM_SUPPORT_EMAIL,PUBLIC_PLATFORM_TWITTER_URL, PUBLIC_PLATFORM_SUPPORT_INVITE, PUBLIC_PLATFORM_DISCORD_URL}: any = globalThis || env;

export const envConfig = {

    PUBLIC_BASE_URL,
	PUBLIC_CRYPTO_PRIVATE_KEY,
	PLATFORM_DATA: {
			name:
				PUBLIC_PLATFORM_NAME || env.PUBLIC_PLATFORM_NAME,
			logo:
				PUBLIC_PLATFORM_LOGO || env.PUBLIC_PLATFORM_LOGO,
			poweredBy:
				PUBLIC_POWERED_BY || env.PUBLIC_POWERED_BY,
			webUrl:
				PUBLIC_PLATFORM_WEB_URL ||
				env.PUBLIC_PLATFORM_WEB_URL,
			orgUrl:
				PUBLIC_POWERED_BY_URL ||
				env.PUBLIC_POWERED_BY_URL,
			docs:
				PUBLIC_PLATFORM_DOCS_URL ||
				env.PUBLIC_PLATFORM_DOCS_URL,
			git:
				PUBLIC_PLATFORM_GIT ||
				env.PUBLIC_PLATFORM_GIT,
			support:
			PUBLIC_PLATFORM_SUPPORT_EMAIL ||
			env.PUBLIC_PLATFORM_SUPPORT_EMAIL,
		
				twitter:
				PUBLIC_PLATFORM_TWITTER_URL ||
				env.PUBLIC_PLATFORM_TWITTER_URL,
				discord:
				PUBLIC_PLATFORM_DISCORD_URL ||
				env.PUBLIC_PLATFORM_DISCORD_URL,
			images: [
				{
					id: 'create_wallet',
					image: createWallet,
				},
			]
		}
}

